### ISSUE TITLE
bedanya apa?

### ISSUE THREAD

**Issue by topanalfa** [alziqziq/vue-ssr-al#1]
**vue ssr** ama **laravel+vue** ada bedanya gak suhu?

**Comment by ziqri-tiketcom** [comment]
laravel + vuekan BE-nya php, kalau ini mirip mirip nuxt, tapi masih cupunya hehehe @topanalfa #CMIIW

**Comment by alziqziq** [comment]
laravel + vuekan BE-nya php, kalau ini mirip mirip nuxt, tapi masih cupunya hehehe @topanalfa #CMIIW
